# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
%define run_testsuite 0
# << macros
%define keepstatic 1

Name:       libsatsolver
Summary:    A new approach to package dependency solving
Version:    0.17.2
Release:    2
Group:      Software Management/Package Manager
License:    BSD 3-clause (or similar)
URL:        https://gitorious.org/opensuse/sat-solver
Source0:    satsolver-%{version}.tar.bz2
Source100:  libsatsolver.yaml
Patch0:     satsolver-evrcmp.patch
Patch1:     0002-Add-armv7tnhl-and-armv7thl-support.patch
Patch2:     0001-Make-libsatsolver-ext-a-versioned-shared-lib.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(rpm)
BuildRequires:  pkgconfig(check)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  doxygen
BuildRequires:  db4-devel
BuildRequires:  perl-devel
BuildRequires:  fdupes
BuildRequires:  expat-devel
BuildRequires:  cmake
BuildRequires:  gcc-c++


%description
A new approach to package dependency solving.


%package demo
Summary:    Applications demoing the satsolver library
License:    BSD 3-clause (or similar)
Group:      Software Management/Package Manager
Requires:   curl
Requires:   gnupg2

%description demo
Applications demoing the satsolver library.

%package -n satsolver-tools
Summary:    A new approach to package dependency solving
License:    BSD 3-clause (or similar)
Group:      Software Management/Package Manager
Requires:   /bin/cp
Requires:   /bin/gzip
Requires:   /usr/bin/bzip2
Provides:   libsatsolver = %{version}-%{release}
Obsoletes:   libsatsolver <= 0.0.15

%description -n satsolver-tools
A new approach to package dependency solving.

%package devel
Summary:    A new approach to package dependency solving
License:    BSD 3-clause (or similar)
Group:      Software Management/Package Manager
Requires:   %{name} = %{version}-%{release}
Requires:   satsolver-tools = %version
Requires:   rpm-devel

%description devel
Development files for satsolver, a new approach to package dependency solving


%prep
%setup -q -n satsolver-%{version}

# satsolver-evrcmp.patch
%patch0 -p1
# 0002-Add-armv7tnhl-and-armv7thl-support.patch
%patch1 -p1
# 0001-Make-libsatsolver-ext-a-versioned-shared-lib.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
export CFLAGS="$RPM_OPT_FLAGS"
export CXXFLAGS="$CFLAGS"
cmake   $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_SITEDIR=%{py_sitedir} -DLIB=%{_lib} -DFEDORA=1 -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_RPATH=1
# << build pre



# >> build post
make %{?jobs:-j%jobs}
make doc_forced
%if 0%{?run_testsuite}
ln -s . build
ctest .
%endif
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make DESTDIR=$RPM_BUILD_ROOT install
# we want to leave the .a file untouched
export NO_BRP_STRIP_DEBUG=true
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig











%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libsatsolver.so.*
%{_libdir}/libsatsolverext.so.*
# << files


%files demo
%defattr(-,root,root,-)
# >> files demo
%{_bindir}/solv
# << files demo

%files -n satsolver-tools
%defattr(-,root,root,-)
# >> files satsolver-tools
%doc LICENSE*
%exclude %{_bindir}/deptestomatic
%exclude %{_bindir}/helix2solv
%exclude %{_bindir}/solv
%{_bindir}/*
# << files satsolver-tools

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libsatsolver.so
%{_libdir}/libsatsolverext.so
%{_libdir}/libsatsolvertools.a
%dir %{_includedir}/satsolver
%{_includedir}/satsolver/*
%{_bindir}/deptestomatic
%{_bindir}/helix2solv
# << files devel

